In [2]:
import pandas as pd

In [13]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0))
print("Current device:", torch.cuda.current_device())

CUDA available: True
GPU name: NVIDIA GeForce RTX 3050 4GB Laptop GPU
Current device: 0


In [14]:
weight=0.9
bias=0.1

In [15]:
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias 

X[:10], y[:10]
     

(tensor([[0.0000],
         [0.0200],
         [0.0400],
         [0.0600],
         [0.0800],
         [0.1000],
         [0.1200],
         [0.1400],
         [0.1600],
         [0.1800]]),
 tensor([[0.1000],
         [0.1180],
         [0.1360],
         [0.1540],
         [0.1720],
         [0.1900],
         [0.2080],
         [0.2260],
         [0.2440],
         [0.2620]]))

In [16]:
train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:] 

len(X_train), len(y_train), len(X_test), len(y_test)

(40, 40, 10, 10)

In [17]:
from torch import nn

In [18]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer= nn.Linear(in_features=1,out_features=2)

    def forward(self,x:torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)


In [19]:
torch.manual_seed(42)
model =LinearRegression()

In [20]:
model.state_dict()

OrderedDict([('linear_layer.weight',
              tensor([[0.7645],
                      [0.8300]])),
             ('linear_layer.bias', tensor([-0.2343,  0.9186]))])

In [21]:
loss_fn=nn.L1Loss()

optimizer=torch.optim.SGD(params=model.parameters(),lr=0.01)

In [22]:
torch.manual_seed(17)

epochs=100


for epoch in range(epochs):
    model.train()


    y_pred=model(X_train)

    loss=loss_fn(y_pred,y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    model.eval()

    with torch.inference_mode():
         test_pred=model(X_test)

         test_loss=loss_fn(test_pred,y_test.type(torch.float))

    if epoch % 10 == 0:
         print(f"Epoch: {epoch} | MAE Train Loss: {loss} | MAE Test Loss: {test_loss} ")

Epoch: 0 | MAE Train Loss: 0.5892084240913391 | MAE Test Loss: 0.5988402366638184 


Epoch: 10 | MAE Train Loss: 0.5316033363342285 | MAE Test Loss: 0.5314850807189941 
Epoch: 20 | MAE Train Loss: 0.4739982485771179 | MAE Test Loss: 0.46412986516952515 
Epoch: 30 | MAE Train Loss: 0.4163932204246521 | MAE Test Loss: 0.39677467942237854 
Epoch: 40 | MAE Train Loss: 0.3587881028652191 | MAE Test Loss: 0.32941946387290955 
Epoch: 50 | MAE Train Loss: 0.3011830747127533 | MAE Test Loss: 0.26206427812576294 
Epoch: 60 | MAE Train Loss: 0.2435780018568039 | MAE Test Loss: 0.19470907747745514 
Epoch: 70 | MAE Train Loss: 0.1953182816505432 | MAE Test Loss: 0.14188717305660248 
Epoch: 80 | MAE Train Loss: 0.1665157526731491 | MAE Test Loss: 0.10820958763360977 
Epoch: 90 | MAE Train Loss: 0.1377132385969162 | MAE Test Loss: 0.07453200966119766 


c:\Users\yashy\anaconda3\envs\pytorch_env\Lib\site-packages\torch\nn\modules\loss.py:128: UserWarning: Using a target size (torch.Size([40, 1])) that is different to the input size (torch.Size([40, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
c:\Users\yashy\anaconda3\envs\pytorch_env\Lib\site-packages\torch\nn\modules\loss.py:128: UserWarning: Using a target size (torch.Size([10, 1])) that is different to the input size (torch.Size([10, 2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


In [23]:
y_pred

tensor([[0.0987, 0.4236],
        [0.1166, 0.4364],
        [0.1345, 0.4491],
        [0.1524, 0.4618],
        [0.1703, 0.4746],
        [0.1882, 0.4873],
        [0.2061, 0.5000],
        [0.2240, 0.5128],
        [0.2419, 0.5255],
        [0.2598, 0.5383],
        [0.2777, 0.5510],
        [0.2956, 0.5637],
        [0.3135, 0.5765],
        [0.3314, 0.5892],
        [0.3493, 0.6020],
        [0.3672, 0.6147],
        [0.3851, 0.6274],
        [0.4030, 0.6402],
        [0.4209, 0.6529],
        [0.4388, 0.6657],
        [0.4567, 0.6784],
        [0.4746, 0.6911],
        [0.4925, 0.7039],
        [0.5105, 0.7166],
        [0.5284, 0.7294],
        [0.5463, 0.7421],
        [0.5642, 0.7548],
        [0.5821, 0.7676],
        [0.6000, 0.7803],
        [0.6179, 0.7930],
        [0.6358, 0.8058],
        [0.6537, 0.8185],
        [0.6716, 0.8313],
        [0.6895, 0.8440],
        [0.7074, 0.8567],
        [0.7253, 0.8695],
        [0.7432, 0.8822],
        [0.7611, 0.8950],
        [0.7